project:
  type: website

website:
  title: "Letten Lab"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - people.qmd
      - publications.qmd
      - join.qmd
      - contact.qmd

  # page-footer:
  #   center: |
  #     © Letten Lab

format:
  html:
    theme: flatly
    css: styles.css
    toc: false