project:
  type: website
  resources:
    - CNAME

website:
  title: "Letten Lab"
  favicon: images/favicon.svg

  navbar:
    logo: images/logo.svg
    logo-alt: "Letten Lab logo"
    left:
      - href: index.qmd
        text: Home
      - people.qmd
      - publications.qmd
      - join.qmd
      - contact.qmd

  page-footer:
    left: |
      © 2026 Letten Lab · University of Queensland
    right:
      - icon: envelope-fill
        href: mailto:a.letten@uq.edu.au
        aria-label: Email
      - icon: mortarboard-fill
        href: https://scholar.google.com.au/citations?user=Z9NWCuEAAAAJ&hl=en
        aria-label: Google Scholar
      - icon: github
        href: https://github.com/andrewletten
        aria-label: GitHub

format:
  html:
    theme: [flatly, theme.scss]
    toc: false
