# Join the Lab

Please email me (a.letten@uq.edu.au) if you are interested in joining the lab (including a CV and brief description of your interests). The work in the the group straddles both theoretical and experimental research. With this in my mind, theoreticians, experimentalists, and everyone in between are equally welcome - maths and programming skills are handy, but so is knowing how to handle a pipette. Scientific curiosity and collegiality are prerequisites. We work closely with the [Engelestaedter lab]() at UQ, including sharing office and lab space, and running joint lab meetings, social events and retreats, with many team members co-advised by both Andrew and Jan. As a combined group, we call ourselves the ALJE lab (not to be confused with an algae lab).    

## Postdocs

I would be delighted to support competitive postdocs in writing fellowship applications. We have had past success with both ARC DECRA and the Marie Curie scheme. Potential fellowships include:

[ARC Discovery Early Career Research award](https://www.arc.gov.au/grants/discovery-program/discovery-early-career-researcher-award-decra) (open to all researchers within five years of PhD) 

[Marie Skłodowska-Curie Actions Global Fellowships](https://ec.europa.eu/research/mariecurieactions/actions/individual-fellowships_en) (open to researchers based in the EU or associated countries) 

[Human Frontier Science Program (HFSP) postdoctoral fellowship](https://www.hfsp.org/funding/hfsp-funding/postdoctoral-fellowships) (open to many researchers from many countries) 

## PhD and Masters

PhD and Masters students should contact me as early as possible in the application cycle (see UQGSS for deadlines). I am very happy to support domestic students in applying for Australian Government Research Training Program Scholarships, and both domestic and international students in applying for [UQ Graduate School Scholarships](https://scholarships.uq.edu.au/scholarship/graduate-school-scholarships-uqgss-%E2%80%93-includes-rtp)

## Honours and Undergraduates

Send me an email or knock on my door (Rm 242 Goddard)!